name: Proof HTML
on:
  push:
    branches:
      main
  pull_request:
  workflow_dispatch:
jobs:
  build-proof:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: anishathalye/proof-html@v1.1.0
        with:
          directory: ./

      - name: Upload proof as artifact
        uses: actions/upload-artifact@v2
        with:
          name: html-proof
          path: proof.png
