name: Proof HTML
on:
  push:
    branches:
      main
  pull_request:
    branches:
      main
  workflow_dispatch:
jobs:
  build-proof:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - uses: anishathalye/proof-html@v2.1.2
        with:
          directory: ./

      - name: Debug outputted files
        run: sudo apt-get install tree -y && tree

      - name: Upload proof as artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: html-proof
          path: tmp
