name: Proof HTML
on:
  push:
    branches:
      main
  workflow_dispatch:
jobs:
  build-proof:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - uses: anishathalye/proof-html@v2.1.2
        with:
          directory: ./

      - name: Debug files
        run: tree

  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run semantic-release
        run: npx semantic-release

