name: Test and Release
on:
  push:
    branches:
      main
  workflow_dispatch:

permissions:
    contents: write

jobs:
  build-proof:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Debug files
        run: tree

      - name: Build proof
        uses: anishathalye/proof-html@v2.1.2
        with:
          directory: ./

  semantic-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: get tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
            dry_run: false # useful for debugging workflow when true
            github_token: ${{ secrets.GITHUB_TOKEN }}
            default_bump: false # minor? will add after v1.0.0
      
