name: Test and Release
on:
  push:
    branches:
      main
  workflow_dispatch:

permissions:
    contents: write
    pages: write
    id-token: write

concurrency: # Only 1 concurrent deployment, skip runs queued between the run in-progress and latest queued
    group: "pages"
    cancel-in-progress: false

jobs:
  spell-check: # Spellcheck the html, markdown, and pdf files
    runs-on: ubuntu-latest
    steps:
      - name: Install pdftotext
        run: sudo apt-get install -y poppler-utils

      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Convert PDF to text
        run: pdftotext files/oz-application.pdf files/application.txt

      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@0.42.0
        with:
          config_path: .github/spellcheck.yml

  build-proof: # Tests the html files ability to be rendered
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Debug files
        run: tree

      - name: Build proof
        uses: anishathalye/proof-html@v2.1.3
        with:
          directory: ./

  semantic-version: # Bumps the version number based on the commit messages
    needs: [build-proof, spell-check]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: get tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
            dry_run: false # useful for debugging workflow when true
            github_token: ${{ secrets.GITHUB_TOKEN }}
            default_bump: patch # minor will replace after v1.0.0 because only new application files are added by non-developers
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

  deploy: # Deploys the application to GitHub Pages
    needs: [semantic-version]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5